export type Question = {
  q: string
  options: [string, string, string, string]
  /** index of correct option, 0-3 */
  answer: 0 | 1 | 2 | 3
  /** difficulty level */
  difficulty?: 'Easy' | 'Hard'
  /** optional image path for circuit diagrams etc */
  image?: string
  /** optional short explanation for hard questions */
  explanation?: string
}

export type Module = {
  title: string
  subject: string
  summary: string
  questions: Question[]
}

export const modules: Module[] = [
  // =====================================================================
  {
    title: "Module I",
    subject: "Data Structures",
    summary: "Fundamental data structures including Arrays, Stacks, Queues, Linked Lists, Trees, and Graphs. Covers asymptotic notation (Big-O, Omega, Theta), sorting algorithms (Quick Sort, Insertion Sort), and Hashing techniques for collision resolution.",
    questions: [
      // --- Algorithms, Complexity & Asymptotic Notation ---
      {
        q: "The measure of the amount of memory an algorithm requires during its execution is called:",
        options: ["Time Complexity", "Space Complexity", "Algorithmic Size", "Processor Load"],
        answer: 1,
        difficulty: "Easy",
      },
      {
        q: "Which asymptotic notation provides a tight bound (both upper and lower) on the growth of an algorithm?",
        options: ["Big-O (O)", "Big-Omega (Ω)", "Theta (Θ)", "Little-o (o)"],
        answer: 2,
        difficulty: "Easy",
      },
      {
        q: "The worst-case time complexity of accessing an element in an array by its index is:",
        options: ["O(1)", "O(n)", "O(log n)", "O(n²)"],
        answer: 0,
        difficulty: "Easy",
      },
      {
        q: "If an algorithm divides the input size by half at each step, its time complexity is typically:",
        options: ["O(n)", "O(n log n)", "O(log n)", "O(n²)"],
        answer: 2,
        difficulty: "Hard",
        explanation: "Binary search is the classic example — it halves the search space each step. This results in O(log n) time since log₂(n) halvings are needed to reach a single element.",
      },
      {
        q: "Big-O notation is primarily used to describe the:",
        options: ["Best-case scenario", "Average-case scenario", "Worst-case scenario", "Memory allocation"],
        answer: 2,
        difficulty: "Easy",
      },
      {
        q: "Which of the following time complexities represents the fastest algorithm for large values of n?",
        options: ["O(n)", "O(n log n)", "O(1)", "O(log n)"],
        answer: 2,
        difficulty: "Hard",
        explanation: "O(1) is constant time — it doesn't grow with input size at all. It beats O(log n), O(n), and O(n log n) for large n.",
      },
      {
        q: "Which notation represents the upper bound of an algorithm's time complexity?",
        options: ["Ω (Omega)", "Θ (Theta)", "O (Big-O)", "δ (Delta)"],
        answer: 2,
        difficulty: "Easy",
      },
      {
        q: "Which of the following best describes time complexity?",
        options: [
          "Amount of memory used by an algorithm",
          "Execution time of an algorithm as input grows",
          "Number of variables in a program",
          "Size of the output",
        ],
        answer: 1,
        difficulty: "Easy",
      },
      // --- Sparse Matrix ---
      {
        q: "A sparse matrix is defined as a matrix in which:",
        options: ["All elements are zero", "Most elements are non-zero", "Most elements are zero", "Diagonal elements are zero"],
        answer: 2,
        difficulty: "Easy",
      },
      {
        q: "To save memory, a sparse matrix is often represented using a 3-tuple format containing:",
        options: ["Row, Column, Value", "Size, Dimension, Value", "X, Y, Z coordinates", "Pointer, Node, Data"],
        answer: 0,
        difficulty: "Easy",
      },
      {
        q: "In the triplet representation of a sparse matrix, the first row typically stores:",
        options: ["The first non-zero element", "Total rows, total columns, and total non-zero elements", "Memory addresses", "Zeros"],
        answer: 1,
        difficulty: "Hard",
        explanation: "The first row of the triplet acts as metadata, storing the matrix dimensions and count of non-zero elements. This helps in memory allocation and traversal.",
      },
      {
        q: "A sparse matrix is best represented using a linked list rather than a 2-D array because it:",
        options: [
          "Reduces access time for all elements",
          "Stores only non-zero elements, saving memory",
          "Eliminates the need for row and column indices",
          "Allows constant-time random access",
        ],
        answer: 1,
        difficulty: "Easy",
      },
      // --- Stacks ---
      {
        q: "A stack follows which underlying principle?",
        options: ["First-In, First-Out (FIFO)", "Last-In, First-Out (LIFO)", "Random Access", "Highest Priority First"],
        answer: 1,
        difficulty: "Easy",
      },
      {
        q: "The operation of adding an element to the top of a stack is called:",
        options: ["Pop", "Enqueue", "Push", "Insert"],
        answer: 2,
        difficulty: "Easy",
      },
      {
        q: "The operation of removing an element from a stack is called:",
        options: ["Pop", "Push", "Dequeue", "Delete"],
        answer: 0,
        difficulty: "Easy",
      },
      {
        q: "What condition occurs when you attempt to pop an element from an empty stack?",
        options: ["Stack Overflow", "Stack Underflow", "Segmentation Fault", "Deadlock"],
        answer: 1,
        difficulty: "Hard",
        explanation: "Underflow is the error when popping from an empty stack (no elements to remove). Overflow is the opposite — pushing onto a full stack.",
      },
      {
        q: "If a stack of size 10 has top = 9, what happens on another push?",
        options: ["Underflow", "Successful insertion", "Overflow", "Stack resets"],
        answer: 2,
        difficulty: "Hard",
        explanation: "With 0-based indexing, top=9 means all 10 slots (0–9) are filled. Another push exceeds capacity, causing a stack overflow.",
      },
      // --- Conversion and Evaluation of Expressions ---
      {
        q: "The expression A + B is written in which format?",
        options: ["Prefix", "Postfix", "Infix", "Polish Notation"],
        answer: 2,
        difficulty: "Easy",
      },
      {
        q: "The postfix equivalent of the infix expression A * B is:",
        options: ["*AB", "AB*", "A*B", "*BA"],
        answer: 1,
        difficulty: "Easy",
      },
      {
        q: "Which data structure is best suited for evaluating postfix expressions?",
        options: ["Queue", "Linked List", "Stack", "Binary Tree"],
        answer: 2,
        difficulty: "Hard",
        explanation: "A stack is used to push operands, then pop and apply operators in the correct order. Its LIFO nature matches the precedence rules of postfix evaluation.",
      },
      {
        q: "Convert the infix expression (A + B) * C to postfix:",
        options: ["ABC*+", "AB+C*", "+AB*C", "*+ABC"],
        answer: 1,
        difficulty: "Hard",
        explanation: "Parentheses force A+B first → AB+. Then multiply by C → AB+C*. Parenthesized sub-expressions are evaluated before outer operators.",
      },
      {
        q: "Which data structure is used to convert an infix expression to a postfix expression?",
        options: ["Queue", "Tree", "Stack", "Array"],
        answer: 2,
        difficulty: "Easy",
      },
      {
        q: "Convert the infix expression A + B * C to postfix:",
        options: ["ABC*+", "AB+C*", "+A*BC", "ABC+*"],
        answer: 0,
        difficulty: "Hard",
        explanation: "Operator precedence: * binds tighter than +. So B*C is evaluated first → BC*. Then A is added → ABC*+.",
      },
      // --- Queues ---
      {
        q: "A queue operates on which principle?",
        options: ["Last-In, First-Out (LIFO)", "First-In, First-Out (FIFO)", "First-In, Last-Out (FILO)", "Random Access"],
        answer: 1,
        difficulty: "Easy",
      },
      {
        q: "In a standard queue, insertions take place at the _____ and deletions take place at the _____.",
        options: ["Front, Rear", "Rear, Front", "Top, Bottom", "Middle, End"],
        answer: 1,
        difficulty: "Easy",
      },
      {
        q: "A circular queue is specifically designed to solve which problem found in a linear queue?",
        options: ["Slow insertion time", "Inability to store strings", "Wastage of memory space", "Difficulty in traversing"],
        answer: 2,
        difficulty: "Hard",
        explanation: "In a linear queue, dequeued slots at the front cannot be reused even if the rear is full. A circular queue wraps around, reusing freed slots.",
      },
      {
        q: "In a circular queue of size N, how is the Rear pointer updated during an enqueue operation?",
        options: ["Rear = Rear + 1", "Rear = (Rear + 1) % N", "Rear = Rear - 1", "Rear = (Rear % N) + 1"],
        answer: 1,
        difficulty: "Hard",
        explanation: "The modulo operator (% N) makes the index wrap around from N-1 back to 0. This is what makes the queue 'circular'.",
      },
      {
        q: "A Deque (Double-Ended Queue) allows insertion and deletion at:",
        options: ["Only the front", "Only the rear", "Both front and rear", "The middle only"],
        answer: 2,
        difficulty: "Easy",
      },
      // --- Linked Lists ---
      {
        q: "A singly linked list node contains:",
        options: ["Data only", "Pointer to next node only", "Data and pointer to the next node", "Data, previous pointer, and next pointer"],
        answer: 2,
        difficulty: "Easy",
      },
      {
        q: "The last node of a singly linked list always points to:",
        options: ["The Head", "NULL", "The previous node", "A random memory address"],
        answer: 1,
        difficulty: "Easy",
      },
      {
        q: "Which linked list allows traversal in both forward and backward directions?",
        options: ["Singly Linked List", "Circular Linked List", "Doubly Linked List", "Stack List"],
        answer: 2,
        difficulty: "Easy",
      },
      {
        q: "In a doubly linked list, each node contains how many pointers?",
        options: ["0", "1", "2", "3"],
        answer: 2,
        difficulty: "Hard",
        explanation: "A DLL node has a 'prev' pointer (to the previous node) and a 'next' pointer (to the next node). These two pointers enable bidirectional traversal.",
      },
      {
        q: "What is the time complexity of deleting the first node of a singly linked list?",
        options: ["O(1)", "O(n)", "O(log n)", "O(n²)"],
        answer: 0,
        difficulty: "Hard",
        explanation: "Deleting the first node only requires updating the head pointer to point to the second node. No traversal is needed, so it's O(1).",
      },
      {
        q: "In a circular linked list, the next pointer of the last node points to:",
        options: ["NULL", "The second node", "The Head (first node)", "The previous node"],
        answer: 2,
        difficulty: "Easy",
      },
      {
        q: "Which of the following is a disadvantage of linked lists compared to arrays?",
        options: ["Fixed size", "Lack of direct/random access to elements", "Inefficient insertions", "Slower deletions at the beginning"],
        answer: 1,
        difficulty: "Hard",
        explanation: "Arrays support O(1) random access via index, but linked lists require sequential traversal. Each node must be visited one by one to reach a target.",
      },
      {
        q: "Time complexity of inserting an element at the beginning of a singly linked list is:",
        options: ["O(1)", "O(n)", "O(log n)", "O(n^2)"],
        answer: 0,
        difficulty: "Easy",
      },
      {
        q: "In a Doubly Linked List, deleting a node requires updating how many pointers?",
        options: ["1", "2", "3", "4"],
        answer: 1,
        difficulty: "Hard",
        explanation: "When deleting a node, you must update the predecessor's 'next' pointer and the successor's 'prev' pointer. That's 2 pointer updates.",
      },
      // --- Trees & Binary Trees ---
      {
        q: "A tree is classified as a:",
        options: ["Linear data structure", "Non-linear data structure", "Stack-based structure", "Queue-based structure"],
        answer: 1,
        difficulty: "Easy",
      },
      {
        q: "In a binary tree, what is the maximum number of children a node can have?",
        options: ["1", "2", "3", "Unlimited"],
        answer: 1,
        difficulty: "Easy",
      },
      {
        q: "The top-most node of a tree is called the:",
        options: ["Leaf", "Branch", "Root", "Edge"],
        answer: 2,
        difficulty: "Easy",
      },
      {
        q: "A full binary tree (or strictly binary tree) is one where every node has either:",
        options: ["0 or 1 child", "1 or 2 children", "0 or 2 children", "Exactly 2 children"],
        answer: 2,
        difficulty: "Hard",
        explanation: "A 'full' (strictly) binary tree means every node is either a leaf (0 children) or an internal node with exactly 2 children. No node has just 1 child.",
      },
      {
        q: "Maximum number of nodes in a binary tree of height h (root at height 0)?",
        options: ["2^h", "2^(h+1) - 1", "2h - 1", "h^2"],
        answer: 1,
        difficulty: "Hard",
        explanation: "Each level l has at most 2^l nodes. Total = 2^0 + 2^1 + ... + 2^h = 2^(h+1) − 1 (geometric series sum).",
      },
      {
        q: "In an array-based binary tree using 0-based indexing, the right child of node at index i is:",
        options: ["2i", "2i + 1", "2i + 2", "i + 2"],
        answer: 2,
        difficulty: "Hard",
        explanation: "With 0-based indexing: left child = 2i+1, right child = 2i+2. For 1-based indexing it would be 2i and 2i+1 respectively.",
      },
      // --- Tree Traversals & BST ---
      {
        q: "Which tree traversal visits nodes in the order: Left Subtree, Root, Right Subtree?",
        options: ["Pre-order", "In-order", "Post-order", "Level-order"],
        answer: 1,
        difficulty: "Easy",
      },
      {
        q: "Which traversal visits nodes in the order: Root, Left Subtree, Right Subtree?",
        options: ["Pre-order", "In-order", "Post-order", "Level-order"],
        answer: 0,
        difficulty: "Easy",
      },
      {
        q: "In a Binary Search Tree (BST), the left child of a node is always _____ the parent, and the right child is always _____ the parent.",
        options: ["Greater than, Less than", "Less than, Greater than", "Equal to, Less than", "Greater than, Equal to"],
        answer: 1,
        difficulty: "Hard",
        explanation: "The BST property requires all left subtree values < parent < all right subtree values. This ordering is the defining characteristic of a BST.",
      },
      {
        q: "Performing an In-order traversal on a Binary Search Tree (BST) will output the elements in:",
        options: ["Random order", "Descending order", "Ascending order", "Unsorted order"],
        answer: 2,
        difficulty: "Hard",
        explanation: "In-order visits Left→Root→Right. Since left < root < right in a BST, the output is automatically in ascending sorted order.",
      },
      {
        q: "The postfix expression traversal is functionally equivalent to which tree traversal?",
        options: ["Pre-order", "In-order", "Post-order", "Level-order"],
        answer: 2,
        difficulty: "Hard",
        explanation: "Post-order visits Left→Right→Root. In expression trees, this yields postfix notation — operands appear before their operator.",
      },
      // --- Graphs ---
      {
        q: "A graph is a collection of:",
        options: ["Stacks and Queues", "Trees and Leaves", "Vertices (Nodes) and Edges", "Arrays and Pointers"],
        answer: 2,
        difficulty: "Easy",
      },
      {
        q: "Which algorithm explores a graph by going as deep as possible before backtracking?",
        options: ["Breadth First Search (BFS)", "Depth First Search (DFS)", "Binary Search", "Quick Sort"],
        answer: 1,
        difficulty: "Easy",
      },
      {
        q: "Depth First Search (DFS) is typically implemented using which underlying data structure?",
        options: ["Queue", "Stack", "Linked List", "Hash Table"],
        answer: 1,
        difficulty: "Hard",
        explanation: "DFS uses a stack (explicit or via recursion's call stack) to track which node to visit next. It goes deep before backtracking.",
      },
      {
        q: "Breadth First Search (BFS) is typically implemented using which underlying data structure?",
        options: ["Queue", "Stack", "Linked List", "Hash Table"],
        answer: 0,
        difficulty: "Hard",
        explanation: "BFS explores level by level, using a queue to process all neighbors before going deeper. FIFO order ensures breadth-first exploration.",
      },
      {
        q: "Which of the following is a common application of graphs?",
        options: ["Evaluating math expressions", "Undo features in editors", "Finding the shortest path in GPS routing", "CPU scheduling"],
        answer: 2,
        difficulty: "Easy",
      },
      {
        q: "Time complexity of BFS on a graph with V vertices and E edges?",
        options: ["O(V)", "O(E)", "O(V + E)", "O(V × E)"],
        answer: 2,
        difficulty: "Hard",
        explanation: "BFS visits every vertex once (O(V)) and examines every edge once (O(E)). Combined, the total work is O(V + E).",
      },
      {
        q: "Which is an application of Depth First Search (DFS)?",
        options: [
          "Finding shortest path in unweighted graph",
          "Level order traversal",
          "Detecting cycles in a graph",
          "Priority scheduling",
        ],
        answer: 2,
        difficulty: "Hard",
        explanation: "DFS can detect back edges during traversal, which indicate cycles. If a visited node is encountered again on the current path, a cycle exists.",
      },
      {
        q: "Space complexity of an adjacency matrix for a graph with V vertices is:",
        options: ["O(V)", "O(E)", "O(V^2)", "O(V + E)"],
        answer: 2,
        difficulty: "Hard",
        explanation: "An adjacency matrix uses a V×V 2D array where each cell indicates an edge. This requires V² space regardless of the number of edges.",
      },
      {
        q: "For a sparse graph with very few edges, the most memory-efficient representation is:",
        options: ["Adjacency matrix", "Incidence matrix", "Adjacency list", "Edge list with sorting"],
        answer: 2,
        difficulty: "Hard",
        explanation: "An adjacency list stores only existing edges, using O(V + E) space. For sparse graphs where E << V², this is much more efficient than a matrix.",
      },
      // --- Sorting Techniques ---
      {
        q: "Which sorting algorithm builds the final sorted array one element at a time by picking the next element and placing it into its correct position?",
        options: ["Quick Sort", "Hashing", "Insertion Sort", "Depth First Search"],
        answer: 2,
        difficulty: "Easy",
      },
      {
        q: "Quick Sort uses which algorithm design paradigm?",
        options: ["Dynamic Programming", "Greedy Method", "Divide and Conquer", "Backtracking"],
        answer: 2,
        difficulty: "Hard",
        explanation: "Quick Sort splits the array around a pivot, then recursively sorts each half. This divide-and-conquer approach gives O(n log n) on average.",
      },
      {
        q: "What is the average-case time complexity of Quick Sort?",
        options: ["O(n²)", "O(n)", "O(n log n)", "O(log n)"],
        answer: 2,
        difficulty: "Hard",
        explanation: "Good pivot choices split the array roughly in half, giving log n levels of recursion, each doing O(n) work. Total: O(n log n).",
      },
      {
        q: "Which sorting technique uses a 'pivot' element to partition the array?",
        options: ["Insertion Sort", "Quick Sort", "Bubble Sort", "Selection Sort"],
        answer: 1,
        difficulty: "Easy",
      },
      {
        q: "Worst-case time complexity of Quick Sort is:",
        options: ["O(n log n)", "O(n)", "O(n^2)", "O(log n)"],
        answer: 2,
        difficulty: "Hard",
        explanation: "Worst case occurs when the pivot is always the smallest or largest element (e.g., already sorted input). This creates n levels with O(n) work each.",
      },
      // --- Hashing ---
      {
        q: "Hashing is primarily used for:",
        options: ["Very fast data retrieval (search)", "Sorting data efficiently", "Drawing graph edges", "Balancing binary trees"],
        answer: 0,
        difficulty: "Easy",
      },
      {
        q: "A 'collision' in hashing occurs when:",
        options: ["The hash table runs out of memory", "Two different keys generate the same hash index", "A key generates a negative index", "The hash function crashes"],
        answer: 1,
        difficulty: "Easy",
      },
      {
        q: "Which hashing method squares the key and uses the middle digits of the result as the index?",
        options: ["Folding Method", "Division Method", "Digit Analysis", "Mid-square Method"],
        answer: 3,
        difficulty: "Hard",
        explanation: "The mid-square method squares the key, then extracts the middle digits as the hash index. Squaring spreads the digits, reducing clustering.",
      },
      {
        q: "In the division method of hashing, the hash function is typically H(k) = k mod M. To minimize collisions, M should ideally be:",
        options: ["An even number", "A power of 2", "A prime number", "A multiple of 10"],
        answer: 2,
        difficulty: "Hard",
        explanation: "A prime M distributes keys more uniformly because it has no common factors with most key patterns. Powers of 2 or even numbers tend to create clustering.",
      },
      {
        q: "Which collision resolution or hash function technique involves breaking the key into equal-sized pieces and adding them together?",
        options: ["Mid-square Method", "Digit Analysis", "Division Method", "Folding Method"],
        answer: 3,
        difficulty: "Hard",
        explanation: "Folding divides the key into equal-length parts and sums them to get the hash index. This spreads the influence of all digits across the result.",
      },
      {
        q: "Which collision resolution technique stores all elements that hash to the same slot in a linked list?",
        options: ["Linear Probing", "Quadratic Probing", "Chaining", "Double Hashing"],
        answer: 2,
        difficulty: "Hard",
        explanation: "Chaining (separate chaining) uses a linked list at each table slot. Colliding elements are simply appended to the list at that index.",
      },
      {
        q: "Digit-analysis hashing yields better key distribution when:",
        options: [
          "Keys are random and uniformly distributed",
          "Keys share common patterns in certain digit positions",
          "Table size is a prime number",
          "Collision resolution uses chaining",
        ],
        answer: 1,
        difficulty: "Hard",
        explanation: "By analyzing the key set, digits with the most variation are selected for hashing. Keys sharing common digit patterns benefit from ignoring uniform positions.",
      },
      {
        q: "Consider the following C program: CountNodes returns 0 if the node is NULL or a leaf (both children NULL), otherwise returns 1 + CountNodes(left) + CountNodes(right). What does CountNodes return when passed the root of a binary tree?",
        options: ["Number of nodes", "Number of leaf nodes", "Number of non-leaf nodes", "Number of leaf nodes minus number of non-leaf nodes"],
        answer: 2,
        difficulty: "Hard",
        explanation: "The function returns 0 for leaves and NULL, but counts 1 for every non-leaf node. So it tallies all internal (non-leaf) nodes in the tree.",
      },
      {
        q: "Consider a hash table of size 7, starting index 0, and hash function (2x + 5) mod 7. If the table is initially empty, what are the contents after inserting 1, 4, 9, 6 using closed hashing?",
        options: ["9, _, 1, 6, _, _, 4", "1, _, 6, 9, _, _, 4", "4, _, 9, 6, _, _, 1", "1, _, 9, 6, _, _, 4"],
        answer: 3,
        difficulty: "Hard",
        explanation: "H(1)=0, H(4)=6, H(9)=2, H(6)=3. Place each at its hash index: 1→idx0, 4→idx6, 9→idx2, 6→idx3. Result: [1, _, 9, 6, _, _, 4].",
      },
      // --- Exam paper questions ---
      {
        q: "What is the time complexity of the following code?\n\nint a=0;\nfor (i=0; i < N; i++) {\n  for (j=N; j > i; j--) {\n    a=a+i+j;\n  }\n}",
        options: ["O(N*Sqrt(N))", "O(N*N)", "O(N*log(N))", "O(N)"],
        answer: 1,
        difficulty: "Hard",
        explanation: "The inner loop runs N, N−1, N−2, ... times forming an arithmetic progression. Total iterations = N(N+1)/2 ≈ O(N²).",
      },
      {
        q: "What is the time complexity of the following code?\n\nint a=0, b=0;\nfor (i=0; i<N; i++) {\n  a=a+rand();\n}\nfor (j=0; j < M; j++) {\n  b=b+rand();\n}",
        options: ["O(N*M) time", "O(N+M) time", "O(N/M) time", "None of these"],
        answer: 1,
        difficulty: "Easy",
        explanation: "The two loops are independent and run sequentially — first O(N) then O(M). Total time = O(N+M).",
      },
      {
        q: "What is the time complexity of the following code?\n\nint i, j, k=0;\nfor (i=n/2; i<=n; i++) {\n  for (j=2; j<=n; j=j*2) {\n    k=k+n/2;\n  }\n}",
        options: ["O(n^2)", "O(n)", "O(n log n)", "O(n^2 Logn)"],
        answer: 2,
        difficulty: "Hard",
        explanation: "The outer loop runs n/2 times → O(n). The inner loop doubles j each step → O(log n). Combined: O(n log n).",
      },
      {
        q: "Which of the following case does not exist in complexity theory?",
        options: ["Best case", "Worst case", "Average case", "Null case"],
        answer: 3,
        difficulty: "Easy",
      },
      {
        q: "Consider the following definition in C programming language. Which of the following C code is used to create a new node?\n\nstruct node { int data; struct node * next; }\ntypedef struct node NODE;\nNODE *ptr;",
        options: [
          "ptr=(NODE*)malloc(NODE);",
          "ptr=(NODE*)malloc(sizeof(NODE));",
          "ptr=(NODE*)malloc(sizeof(NODE*));",
          "ptr=(NODE)malloc(sizeof(NODE));",
        ],
        answer: 1,
        difficulty: "Hard",
        explanation: "malloc requires the size in bytes of the type being allocated. sizeof(NODE) returns the correct byte size of the struct. The result must be cast to (NODE*).",
      },
    ],
  },

  // =====================================================================
  {
    title: "Module II",
    subject: "Logic Circuit Design",
    summary: "Number systems (Binary, Octal, Hex, BCD, Gray code), Boolean Algebra, and logic gates. Combinational logic design including multiplexers, decoders, and adders. Sequential logic focusing on Flip-flops (SR, D, JK, T), Registers, and Counters.",
    questions: [
      {
        q: "Which number system uses base 2?",
        options: ["Decimal", "Binary", "Octal", "Hexadecimal"],
        answer: 1,
      },
      {
        q: "Which number system maps exactly 4 bits to one digit, used as binary shorthand?",
        options: ["Octal", "Hexadecimal", "Decimal", "BCD"],
        answer: 1,
      },
      {
        q: "Which digit is NOT valid in the octal number system?",
        options: ["3", "5", "7", "8"],
        answer: 3,
      },
      {
        q: "The hexadecimal equivalent of decimal 15 is:",
        options: ["E", "D", "F", "10"],
        answer: 2,
      },
      {
        q: "Result of the hexadecimal subtraction (1A)16 − (0B)16:",
        options: ["(0F)16", "(11)16", "(10)16", "(09)16"],
        answer: 0,
      },
      {
        q: "Sum of (17)8 and (12)8 in octal:",
        options: ["(29)8", "(31)8", "(21)8", "(30)8"],
        answer: 1,
      },
      {
        q: "Octal 745 converted to hexadecimal is:",
        options: ["F5", "1E5", "3E5", "7A5"],
        answer: 1,
      },
      {
        q: "In signed 2's complement, the 8-bit value 11111101 represents:",
        options: ["-3", "-2", "-1", "-5"],
        answer: 0,
      },
      {
        q: "Which signed representation eliminates both +0 and −0?",
        options: ["Sign-magnitude", "One's complement", "Two's complement", "Excess-3"],
        answer: 2,
      },
      {
        q: "−0.625 in fixed-point binary with 3 fractional bits (sign-magnitude) is:",
        options: ["1.011", "0.101", "1.101", "0.011"],
        answer: 2,
      },
      {
        q: "Which representation allows very large and very small numeric values?",
        options: ["Fixed point", "BCD", "Floating point", "Gray code"],
        answer: 2,
      },
      {
        q: "Increasing the exponent bits of a floating-point format primarily:",
        options: [
          "Increases precision",
          "Reduces rounding error",
          "Increases dynamic range",
          "Speeds up computation",
        ],
        answer: 2,
      },
      {
        q: "BCD stands for:",
        options: ["Binary Coded Decimal", "Binary Calculated Digit", "Bit Coded Decimal", "Binary Coded Dual"],
        answer: 0,
      },
      {
        q: "Adding BCD digits 7 and 8 (with BCD correction) gives:",
        options: ["1111", "0101 0000", "0001 0101", "0001 0011"],
        answer: 2,
      },
      {
        q: "The Gray code is a:",
        options: ["Weighted code", "Cyclic / Unit-distance code", "Sequential code", "Alphanumeric code"],
        answer: 1,
      },
      {
        q: "Binary 11011 in Gray code is:",
        options: ["10110", "11110", "10111", "10101"],
        answer: 0,
      },
      {
        q: "Excess-3 code is also known as:",
        options: ["BCD + 2", "BCD + 3", "Self-complementing code", "Both B and C"],
        answer: 3,
      },
      {
        q: "Decimal 9 in 4-bit Excess-3 code is:",
        options: ["1001", "1100", "1111", "1010"],
        answer: 1,
      },
      {
        q: "According to De Morgan's theorem, A·B equals:",
        options: ["A'·B'", "A+B", "A'+B'", "A+B"],
        answer: 2,
      },
      {
        q: "Which Boolean law states A + A' = 1?",
        options: ["Commutative law", "Associative law", "Complement law", "Distributive law"],
        answer: 2,
      },
      {
        q: "The principle of duality states that an expression remains valid if:",
        options: [
          "ANDs are swapped with ORs",
          "1s are swapped with 0s",
          "Variables are complemented",
          "Both A and B",
        ],
        answer: 3,
      },
      {
        q: "Which form represents a Boolean function as a sum of minterms?",
        options: ["POS", "SOP", "Canonical POS", "Product form"],
        answer: 1,
      },
      {
        q: "Which gate is a universal gate?",
        options: ["AND", "OR", "NAND", "XOR"],
        answer: 2,
      },
      {
        q: "Karnaugh map is mainly used for:",
        options: [
          "Boolean expression evaluation",
          "Code conversion",
          "Logic circuit simulation",
          "Minimization of Boolean expressions",
        ],
        answer: 3,
      },
      {
        q: "In K-map minimization, a group of 8 adjacent cells (octet) eliminates:",
        options: ["2 variables", "3 variables", "4 variables", "8 variables"],
        answer: 1,
      },
      {
        q: "Simplify F = A·(A' + B):",
        options: ["A", "B", "A·B", "A+B"],
        answer: 2,
      },
      {
        q: "K-map for F(A,B,C) with minterms m(0,2,4,6) simplifies to:",
        options: ["A", "C", "C'", "B'"],
        answer: 2,
      },
      {
        q: "Which combinational circuit converts a decimal number into a binary code?",
        options: ["Decoder", "Encoder", "Multiplexer", "Demultiplexer"],
        answer: 1,
      },
      {
        q: "How many select lines are required for a 16-to-1 Multiplexer?",
        options: ["2", "3", "4", "8"],
        answer: 2,
      },
      {
        q: "How many 4-to-1 MUX are needed to construct a 16-to-1 MUX?",
        options: ["4", "5", "3", "16"],
        answer: 1,
      },
      {
        q: "In a 4:1 MUX with select S1S0 = 10, the input appearing at output is:",
        options: ["D0", "D1", "D2", "D3"],
        answer: 2,
      },
      {
        q: "Which device performs the reverse operation of an encoder?",
        options: ["Decoder", "Multiplexer", "Demultiplexer", "Comparator"],
        answer: 0,
      },
      {
        q: "A 2-to-4 line decoder with an enable input can also act as:",
        options: ["Multiplexer", "Demultiplexer", "Encoder", "Adder"],
        answer: 1,
      },
      {
        q: "In a 3-to-8 decoder, applying input 101 activates:",
        options: ["One output Y5", "Two outputs Y1 and Y5", "One output Y1", "All outputs"],
        answer: 0,
      },
      {
        q: "A Half Adder consists of which two logic gates?",
        options: ["AND and OR", "XOR and AND", "XOR and OR", "NAND and NOR"],
        answer: 1,
      },
      {
        q: "Which adder adds three input bits?",
        options: ["Half adder", "Full adder", "Parallel adder", "Ripple carry adder"],
        answer: 1,
      },
      {
        q: "A Full Subtractor requires how many inputs?",
        options: ["2", "3", "4", "1"],
        answer: 1,
      },
      {
        q: "To implement a Full Adder using two Half Adders, the additional gate required is:",
        options: ["AND", "OR", "NOT", "XOR"],
        answer: 1,
      },
      {
        q: "In a 4-bit ripple carry adder with 10 ns per full adder, worst-case delay is:",
        options: ["10 ns", "20 ns", "30 ns", "40 ns"],
        answer: 3,
      },
      {
        q: "In an S–R flip-flop, S=1 and R=1 is invalid because:",
        options: [
          "Output oscillates continuously",
          "Both outputs become 0, violating complementarity",
          "Clock signal is disabled",
          "Produces a metastable state only",
        ],
        answer: 1,
      },
      {
        q: "The 'Race Around Condition' is a problem in which flip-flop?",
        options: ["SR Flip-flop", "D Flip-flop", "JK Flip-flop", "T Flip-flop"],
        answer: 2,
      },
      {
        q: "In a JK flip-flop, when J=1 and K=1, the next state Qn+1 is:",
        options: ["0", "1", "No change", "Q'n (Toggle)"],
        answer: 3,
      },
      {
        q: "Which flip-flop is essentially a JK with J and K tied together?",
        options: ["D Flip-flop", "T Flip-flop", "RS Flip-flop", "Master-Slave Flip-flop"],
        answer: 1,
      },
      {
        q: "Master–Slave JK flip-flop is preferred mainly to:",
        options: [
          "Reduce power consumption",
          "Simplify combinational logic",
          "Eliminate the race-around condition",
          "Allow asynchronous operation",
        ],
        answer: 2,
      },
      {
        q: "Which shift register loads data all at once and shifts out one bit at a time?",
        options: ["SISO", "SIPO", "PISO", "PIPO"],
        answer: 2,
      },
      {
        q: "A SIPO shift register converts:",
        options: ["Serial to serial", "Parallel to serial", "Serial to parallel", "Parallel to parallel"],
        answer: 2,
      },
      {
        q: "A PIPO register storing a 4-bit word needs how many clock cycles to load?",
        options: ["1", "4", "0", "8"],
        answer: 0,
      },
      {
        q: "A Ring Counter with n flip-flops has how many distinct states?",
        options: ["n", "2^n", "2n", "n − 1"],
        answer: 0,
      },
      {
        q: "A Johnson counter with 5 flip-flops produces how many states?",
        options: ["5", "10", "32", "25"],
        answer: 1,
      },
      {
        q: "In an Asynchronous counter, the maximum operating frequency is limited because:",
        options: [
          "All flip-flops are clocked simultaneously",
          "Cumulative propagation delay causes incorrect transitions",
          "More hardware is required",
          "Clock skew is eliminated",
        ],
        answer: 1,
      },
      {
        q: "For a 3-bit synchronous DOWN counter, the next state after 000 is:",
        options: ["001", "111", "110", "101"],
        answer: 1,
      },
      {
        q: "In Verilog, which keyword represents a physical connection between structural elements?",
        options: ["Reg", "Wire", "Integer", "Parameter"],
        answer: 1,
      },
      {
        q: "Which Verilog modeling style uses an always block to describe logic?",
        options: ["Gate-level", "Structural", "Behavioral", "Literal"],
        answer: 2,
      },
      {
        q: "Verilog half adder: assign Sum = A ^ B; assign Carry = ___;",
        options: ["A | B", "A & B", "A ~^ B", "A + B"],
        answer: 1,
      },
      {
        q: "A 4-bit Ripple counter consists of Flip-Flops, each with a propagation delay from clock to Q output of 15ns. For the counter to recycle from 1111 to 0000, it takes a total of:",
        options: ["30ns", "45ns", "15ns", "60ns"],
        answer: 3,
        difficulty: "Hard",
        explanation: "All 4 flip-flops must toggle sequentially in a ripple counter. Total delay = 4 × 15ns = 60ns as each flip-flop waits for the previous one.",
      },
      {
        q: "The number of Boolean functions that can be generated by n-variables is equal to:",
        options: ["2ⁿ", "2^(2ⁿ)", "2^(n−1)", "−2ⁿ"],
        answer: 1,
        difficulty: "Hard",
        explanation: "n variables produce 2ⁿ possible input combinations (rows in truth table). Each combination can be 0 or 1, giving 2^(2ⁿ) total functions.",
      },
      {
        q: "In an 8-bit Johnson counter sequence, how many states orbit patterns are possible?",
        options: ["240", "228", "232", "220"],
        answer: 0,
        difficulty: "Hard",
        explanation: "An n-bit Johnson counter produces 2n valid states. The remaining 2ⁿ − 2n states form various orbit patterns. For n=8: (256−16)/1 orbit patterns = 240.",
      },
      {
        q: "Which of the following is a valid HDL modeling technique?",
        options: ["Behavioral", "Logical", "Algorithmic", "Software-based"],
        answer: 0,
        difficulty: "Easy",
      },
      {
        q: "In a 100 kHz clock frequency, 16 bits can be serially entered into a shift register in:",
        options: ["150 micro-sec", "160 micro-sec", "170 micro-sec", "180 micro-sec"],
        answer: 1,
        difficulty: "Hard",
        explanation: "Period = 1/100kHz = 10 µs per bit. 16 bits × 10 µs = 160 µs total time to shift in all bits serially.",
      },
      {
        q: "What are the minimum number of 2-to-1 multiplexers required to generate a 2-input AND gate and a 2-input EX-OR gate?",
        options: ["1 and 2", "1 and 3", "1 and 1", "2 and 2"],
        answer: 1,
        difficulty: "Hard",
        explanation: "A 2:1 MUX with one input tied to 0 implements AND (1 MUX). XOR requires cascading 3 MUXes to handle the complementary logic.",
      },
      {
        q: "A mod-n counter using a synchronous binary up-counter with synchronous clear input is shown. gate to the CLEAR input. The value of n is:",
        options: ["7", "10", "15", "20"],
        answer: 0,
        difficulty: "Hard",
        image: "/mod10_counter.png",
        explanation: "The AND gate detects state 0110 (decimal 6) and triggers CLEAR, resetting the counter. So it counts 0–6 (7 states), making it mod-7.",
      },
      // --- New additions ---
      {
        q: "A full adder can be made out of:",
        options: ["Two half adders", "Two half adders and an OR gate", "Two half adders and a NOT gate", "Three half adders"],
        answer: 1,
        difficulty: "Hard",
        explanation: "Two half adders generate partial sum and carry bits. The OR gate combines the two carry outputs to produce the final carry-out.",
      },
      {
        q: "The 2's complement representation of -17 is:",
        options: ["101111", "100001", "110011", "101110"],
        answer: 0,
        difficulty: "Hard",
        explanation: "+17 in 6-bit binary is 010001. The 1's complement is 101110. Adding 1 gives the 2's complement: 101111.",
      },
      {
        q: "A digital circuit that can store only one bit is a:",
        options: ["NOR gate", "Register", "Flip-flop", "XOR gate"],
        answer: 2,
        difficulty: "Easy",
      },
      {
        q: "A 4-bit ripple counter and a 4-bit synchronous counter are made using flip-flops having a propagation delay of 10ns each. If the worst-case delay in the ripple counter and the synchronous counter be R and S respectively, then:",
        options: ["R = 10ns, S = 40ns", "R = 40ns, S = 10ns", "R = 10ns, S = 30ns", "R = 30ns, S = 10ns"],
        answer: 1,
        difficulty: "Hard",
        explanation: "In a ripple counter, delay cascades through all flip-flops: 4 × 10ns = 40ns. In a synchronous counter, all flip-flops are clocked simultaneously, so delay = 10ns.",
      },
      {
        q: "The circuit of the given figure realizes the function:",
        options: ["Y = (A̅+B̅)C + D̅E̅", "Y = A̅+B̅+C̅+D̅+E̅", "AB + C + DE", "AB + C(D+E)"],
        answer: 0,
        difficulty: "Hard",
        image: "/logic.png",
        explanation: "Top NAND(A,B)=A̅B̅→(A̅+B̅). Middle NAND with C gives (A̅+B̅)·C. Bottom NAND(D,E)=D̅E̅ inverted back to DE. Final NAND combines them: Y=(A̅+B̅)C+D̅E̅.",
      },
    ],
  },

  // =====================================================================
  {
    title: "Module III",
    subject: "Computer Organization and Architecture",
    summary: "Computer arithmetic including floating point operations and Booth's algorithm. Memory hierarchy covering Cache mapping, virtual memory, and main memory. Instruction formats, addressing modes, pipelining, and basic I/O interfacing (DMA, Interrupts).",
    questions: [
      {
        q: "Which functional unit performs arithmetic and logical operations?",
        options: ["Control Unit", "Memory Unit", "Arithmetic Logic Unit", "Input Unit"],
        answer: 2,
      },
      {
        q: "Which functional unit controls and coordinates all other units?",
        options: ["ALU", "Register", "Control Unit", "Cache"],
        answer: 2,
      },
      {
        q: "A system bus is used to:",
        options: [
          "Store data",
          "Perform computation",
          "Transfer data, address and control signals between units",
          "Decode instructions",
        ],
        answer: 2,
      },
      {
        q: "A memory location is identified by its:",
        options: ["Data value", "Instruction", "Address", "Size"],
        answer: 2,
      },
      {
        q: "Which memory operation reads data from memory?",
        options: ["Write", "Fetch", "Read", "Execute"],
        answer: 2,
      },
      {
        q: "During a memory read, the correct sequence is:",
        options: [
          "Address placed on bus, read signal asserted, data transferred to CPU",
          "Data placed on bus then address",
          "CPU writes data first then reads address",
          "Memory writes to disk first",
        ],
        answer: 0,
      },
      {
        q: "A byte-addressable memory stores a 32-bit word starting at 0x1004 (big-endian). The MSB is at:",
        options: ["0x1004", "0x1005", "0x1006", "0x1007"],
        answer: 0,
      },
      {
        q: "Addressing modes are used to:",
        options: [
          "Increase memory size",
          "Reduce instruction length",
          "Specify how operands are accessed",
          "Speed up ALU operations",
        ],
        answer: 2,
      },
      {
        q: "Which addressing mode places the operand's actual memory address directly in the instruction?",
        options: ["Immediate", "Register", "Direct", "Indirect"],
        answer: 2,
      },
      {
        q: "Which addressing mode requires two memory accesses to fetch the operand?",
        options: ["Immediate addressing", "Register addressing", "Direct addressing", "Indirect addressing"],
        answer: 3,
      },
      {
        q: "Instruction sequencing in a CPU is supported primarily by which register?",
        options: ["Accumulator", "Program Counter (PC)", "Instruction Register", "Stack Pointer"],
        answer: 1,
      },
      {
        q: "The instruction cycle consists of:",
        options: ["Fetch only", "Decode only", "Execute only", "Fetch, Decode and Execute"],
        answer: 3,
      },
      {
        q: "During the fetch phase, the correct micro-operation sequence is:",
        options: [
          "MDR ← Memory; IR ← MDR; PC ← PC + 1",
          "MAR ← PC; MDR ← Memory[MAR]; IR ← MDR; PC ← PC + 1",
          "IR ← PC; MAR ← MDR; PC ← PC − 1",
          "MAR ← IR; MDR ← Memory; PC ← PC + 1",
        ],
        answer: 1,
      },
      {
        q: "If PC = 400 and instruction length is 4 bytes, after fetch (branch not taken) PC becomes:",
        options: ["400", "401", "404", "Depends on branch"],
        answer: 2,
      },
      {
        q: "Register Transfer Logic (RTL) is mainly used to describe:",
        options: [
          "Data storage in memory",
          "Micro-operations / transfer of data between registers",
          "Instruction decoding",
          "ALU design",
        ],
        answer: 1,
      },
      {
        q: "RTL R2 ← R1 + R3 implies:",
        options: [
          "Data transfer without computation",
          "ALU arithmetic operation with register operands",
          "Memory-to-register transfer",
          "Control unit state transition only",
        ],
        answer: 1,
      },
      {
        q: "Arithmetic and shift micro-operations are executed by:",
        options: ["Control Unit", "Arithmetic Logic Unit (ALU)", "Cache", "DMA controller"],
        answer: 1,
      },
      {
        q: "Which algorithm is commonly used for binary multiplication of signed numbers?",
        options: ["Booth's algorithm", "Euclid's algorithm", "Dijkstra's algorithm", "Huffman algorithm"],
        answer: 0,
      },
      {
        q: "Booth's algorithm is mainly used to:",
        options: [
          "Reduce hardware cost",
          "Handle signed numbers efficiently",
          "Increase clock speed",
          "Eliminate carry propagation",
        ],
        answer: 1,
      },
      {
        q: "Which multiplier generates partial products simultaneously?",
        options: ["Booth multiplier", "Sequential multiplier", "Array multiplier", "Wallace tree multiplier"],
        answer: 2,
      },
      {
        q: "Pipelining improves processor performance by:",
        options: [
          "Reducing instruction size",
          "Increasing clock period",
          "Overlapping instruction execution",
          "Reducing memory size",
        ],
        answer: 2,
      },
      {
        q: "Which is an example of an arithmetic pipeline?",
        options: ["Instruction fetch", "Floating-point addition", "Interrupt handling", "Cache access"],
        answer: 1,
      },
      {
        q: "A data hazard in a pipeline occurs when:",
        options: [
          "Two instructions need same hardware",
          "Control flow changes",
          "An instruction depends on a previous instruction's result",
          "An interrupt occurs",
        ],
        answer: 2,
      },
      {
        q: "Hard-wired control is characterized by:",
        options: [
          "High flexibility",
          "Slow operation",
          "Use of microinstructions",
          "Fast operation but less flexible",
        ],
        answer: 3,
      },
      {
        q: "A key disadvantage of hard-wired control is:",
        options: [
          "Use of microinstructions",
          "Difficulty modifying the instruction set",
          "High cost of control memory",
          "Slow execution speed",
        ],
        answer: 1,
      },
      {
        q: "In microprogrammed control, control signals are generated by:",
        options: ["ALU", "Control memory", "Cache", "Register file"],
        answer: 1,
      },
      {
        q: "The microprogram sequencer is responsible for:",
        options: [
          "Decoding opcode directly into control signals",
          "Selecting and sequencing the next microinstruction address",
          "Executing arithmetic micro-operations",
          "Handling interrupt prioritization",
        ],
        answer: 1,
      },
      {
        q: "Horizontal microinstructions differ from vertical ones in:",
        options: [
          "Smaller control memory",
          "Fewer control signals per microinstruction",
          "Higher parallelism with wider words",
          "Slower execution due to decoding",
        ],
        answer: 2,
      },
      {
        q: "Which mechanism allows an I/O device to transfer data directly to memory without continuous CPU intervention?",
        options: ["Programmed I/O", "Interrupt-driven I/O", "Direct Memory Access (DMA)", "Memory-mapped I/O"],
        answer: 2,
      },
      {
        q: "Interrupt hardware in a real-time system is mainly designed to:",
        options: [
          "Reduce memory access latency",
          "Allow immediate response to asynchronous external events",
          "Eliminate polling completely",
          "Increase instruction throughput",
        ],
        answer: 1,
      },
      {
        q: "Semiconductor RAM differs from ROM in that RAM:",
        options: [
          "Is non-volatile",
          "Allows both read and write during normal execution",
          "Is used only for firmware",
          "Does not require address decoding",
        ],
        answer: 1,
      },
      {
        q: "Which memory stores permanent programs (firmware)?",
        options: ["RAM", "Cache", "ROM", "CAM"],
        answer: 2,
      },
      {
        q: "Cache mapping that allows any block to map to any line is:",
        options: ["Direct mapping", "Associative mapping", "Set-associative mapping", "Linear mapping"],
        answer: 1,
      },
      {
        q: "Which cache mapping offers a practical compromise between hardware complexity and hit ratio?",
        options: ["Direct mapping", "Fully associative mapping", "Set-associative mapping", "Random mapping"],
        answer: 2,
      },
      {
        q: "Content Addressable Memory (CAM) is accessed by:",
        options: ["Address only", "Content / data value", "Sequential index", "Disk block number"],
        answer: 1,
      },
      {
        q: "Consider a direct mapped cache of size 256 Kilo words with block size 512 words. There are 6 bits in the tag. The number of bits in block (index) and word (offset) fields of physical address are:",
        options: ["block (index) = 6 bits, word (offset) = 9 bits", "block (index) = 7 bits, word (offset) = 8 bits", "block (index) = 9 bits, word (offset) = 9 bits", "block (index) = 8 bits, word (offset) = 8 bits"],
        answer: 2,
        difficulty: "Hard",
        explanation: "256K/512 = 512 blocks → 9 index bits. 512 words/block → 9 offset bits. Tag = 6 bits. Total address = 6+9+9 = 24 bits.",
      },
      {
        q: "The memory unit of a computer has 1 Giga words of 64 bits each. The instruction format has 4 fields: an opcode field; a mode field for 12 addressing modes; a register address field for 48 registers; and a memory address field. If an instruction is 64 bits long, how large is the opcode field?",
        options: ["34 bits", "24 bits", "20 bits", "14 bits"],
        answer: 1,
        difficulty: "Hard",
        explanation: "1G = 2³⁰ words → 30-bit address. Mode: ceil(log₂ 12)=4 bits. Registers: ceil(log₂ 48)=6 bits. Opcode = 64−30−4−6 = 24 bits.",
      },
      {
        q: "A computer has 64-bit instructions and a 28-bit address. Suppose there are 252 two-address instructions. How many 1-address instructions can be formulated?",
        options: ["2^24", "2^26", "2^28", "2^30"],
        answer: 3,
        difficulty: "Hard",
        explanation: "Opcode for 2-addr = 64−28−28 = 8 bits. 2⁸−252 = 4 unused opcodes expand into 1-addr space. 4 × 2²⁸ = 2² × 2²⁸ = 2³⁰.",
      },
      {
        q: "Determine the number of clock cycles required to process 200 tasks in a six-segment pipeline (assume no stalls, each segment takes 1 cycle):",
        options: ["1200 cycles", "206 cycles", "207 cycles", "205 cycles"],
        answer: 3,
        difficulty: "Hard",
        explanation: "Pipeline formula: k + (n−1) cycles, where k=stages, n=tasks. So 6 + (200−1) = 6 + 199 = 205 cycles.",
      },
      {
        q: "Match: P.DMA  Q.Processor Status Word  R.Daisy Chaining  S.Handshaking with 1.Priority Interrupt 2.I/O Transfer 3.CPU 4.Asynchronous Data Transfer",
        options: ["P-1, Q-3, R-4, S-2", "P-2, Q-3, R-1, S-4", "P-2, Q-1, R-3, S-4", "P-4, Q-3, R-1, S-2"],
        answer: 1,
        difficulty: "Hard",
        explanation: "DMA handles I/O transfer (P-2). PSW belongs to the CPU (Q-3). Daisy chaining is a priority interrupt scheme (R-1). Handshaking is asynchronous data transfer (S-4).",
      },
      {
        q: "A computer uses 32-bit byte addressing with a 2-way set associative cache of 32KB capacity. Each cache block contains 16 bytes. The number of bits in TAG, SET, and OFFSET fields are:",
        options: ["TAG=18, SET=10, OFFSET=4", "TAG=16, SET=12, OFFSET=4", "TAG=20, SET=10, OFFSET=2", "TAG=16, SET=8, OFFSET=8"],
        answer: 0,
        difficulty: "Hard",
        explanation: "32KB/16B = 2048 blocks. 2-way → 1024 sets → 10 set bits. 16B block → 4 offset bits. Tag = 32−10−4 = 18 bits.",
      },
      {
        q: "The Booth recoded form of -6 is:",
        options: ["-1 +1 0 -1 0", "+1 -1 +1 -1 0", "0 -1 +1 -1 0", "0 +1 -1 +1 0"],
        answer: 2,
        difficulty: "Hard",
        explanation: "-6 in binary (2's complement) is 11010. Appending 0: 110100. Scanning pairs right-to-left and applying Booth's recoding gives 0 -1 +1 -1 0.",
      },
      // --- Exam paper questions ---
      {
        q: "Which of the following is NOT a special-purpose register used by the CPU?",
        options: ["Program Counter (PC)", "Stack Pointer", "Accumulator", "Memory Address Register (MAR)"],
        answer: 2,
        difficulty: "Hard",
        explanation: "The PC, Stack Pointer, and MAR serve highly specific operational roles. The Accumulator, while important, is generally considered a general-purpose data register for ALU operations.",
      },
      {
        q: "_____ is the branch logic that provides decision-making capabilities in the control unit:",
        options: ["Unconditional transfer", "Conditional transfer", "Both A and B", "None of these"],
        answer: 1,
        difficulty: "Easy",
        explanation: "Conditional transfer evaluates a condition (e.g., zero flag, carry flag) and branches accordingly, providing the decision-making capability inside the control unit.",
      },
      {
        q: "The size of virtual memory depends on the size of the:",
        options: ["Data bus", "Main memory", "Address bus", "None of the above"],
        answer: 2,
        difficulty: "Easy",
        explanation: "The address bus determines how many unique memory addresses can be generated. A 32-bit address bus can address 2³² locations, defining the maximum virtual address space.",
      },
      {
        q: "Which of the following architectures is more power efficient?",
        options: ["RISC", "CISC", "Both A and B", "None of the above"],
        answer: 0,
        difficulty: "Easy",
        explanation: "RISC (Reduced Instruction Set Computer) uses simpler instructions with fewer transistors and reduced circuit complexity, making it inherently more power efficient than CISC.",
      },
      {
        q: "What does VLIW stand for?",
        options: ["Very Large Instruction Word", "Very Long Instruction Word", "Very Long Instruction Width", "Very Large Instruction Width"],
        answer: 1,
        difficulty: "Easy",
      },
      {
        q: "The main components (or basic units) of a computer system are:",
        options: ["Central Processing Unit (CPU)", "Input/Output unit", "Memory unit (Storage unit)", "All of the above"],
        answer: 3,
        difficulty: "Easy",
      },
      {
        q: "If the main memory is 8K words and the cache memory is 2K words, using associative mapping. Each word of cache memory shall be how many bits wide (data word = 16 bits)?",
        options: ["11 bits", "21 bits", "16 bits", "20 bits"],
        answer: 2,
        difficulty: "Hard",
        explanation: "With associative mapping, each cache line stores a tag (13 bits for 8K addresses) plus the data word (16 bits) = 29 bits total. However, this classic exam question treats the word width as 16 bits (data only).",
      },
      {
        q: "The effective address of the instruction MUL 5(R1, R2) is:",
        options: ["5+[R1]+[R2]", "5×([R1]+[R2])", "5+R1×R2", "5+R1+R2"],
        answer: 0,
        difficulty: "Hard",
        explanation: "This is indexed addressing mode with two base registers. The effective address = offset + content of R1 + content of R2 = 5 + [R1] + [R2].",
      },
    ],
  },

  // =====================================================================
  {
    title: "Module IV",
    subject: "Operating Systems",
    summary: "Core OS functions and process management. CPU scheduling algorithms (FCFS, SJF, Round Robin). Process synchronization, deadlocks, memory management (paging, segmentation), and file system implementation.",
    questions: [
      {
        q: "The primary role of an operating system is:",
        options: [
          "Program execution only",
          "Resource management and abstraction between hardware and user",
          "User interface only",
          "Data storage",
        ],
        answer: 1,
      },
      {
        q: "Which OS service allows programs to request services from the kernel?",
        options: ["Interrupts", "System calls", "Context switching", "Scheduling"],
        answer: 1,
      },
      {
        q: "Which system call creates a new process in UNIX?",
        options: ["exec()", "wait()", "fork()", "exit()"],
        answer: 2,
      },
      {
        q: "In a layered OS, the main advantage is:",
        options: [
          "Faster execution due to parallel layers",
          "Easier debugging and modular verification",
          "Elimination of hardware dependency",
          "Reduced memory footprint",
        ],
        answer: 1,
      },
      {
        q: "In a microkernel architecture, which service typically runs in user space?",
        options: ["Process management", "Memory management", "Device drivers", "Scheduling"],
        answer: 2,
      },
      {
        q: "A microkernel improves system reliability primarily because:",
        options: [
          "It places all services in kernel space",
          "Reduced kernel size limits the impact of failures",
          "It eliminates system calls",
          "It avoids inter-process communication",
        ],
        answer: 1,
      },
      {
        q: "Which step occurs first in the system boot process?",
        options: ["Loading OS kernel", "Power-on self-test (POST)", "User login", "Process scheduling"],
        answer: 1,
      },
      {
        q: "Which IPC mechanism allows processes to share a common address space?",
        options: ["Message passing", "Pipes", "Shared memory", "Signals"],
        answer: 2,
      },
      {
        q: "In message-passing IPC, processes exchange data by:",
        options: [
          "Reading and writing shared variables",
          "Sending and receiving messages through the kernel",
          "Accessing common files only",
          "Using global registers",
        ],
        answer: 1,
      },
      {
        q: "Which scheduling algorithm is non-preemptive?",
        options: ["Round Robin", "Shortest Remaining Time", "First Come First Served", "Priority (preemptive)"],
        answer: 2,
        difficulty: "Easy",
      },
      {
        q: "In FCFS scheduling, the process that arrives first is:",
        options: ["Executed last", "Executed first", "Ignored", "Preempted"],
        answer: 1,
        difficulty: "Easy",
      },
      {
        q: "The main disadvantage of FCFS is:",
        options: ["Starvation", "Deadlock", "Convoy effect", "Preemption"],
        answer: 2,
        difficulty: "Easy",
      },
      {
        q: "SJF scheduling minimizes:",
        options: ["Turnaround time", "CPU utilization", "Average waiting time", "Response time"],
        answer: 2,
        difficulty: "Easy",
      },
      {
        q: "Which scheduling algorithm may cause starvation?",
        options: ["FCFS", "SJF", "Round Robin", "FIFO"],
        answer: 1,
        difficulty: "Hard",
        explanation: "SJF can cause starvation for longer processes if shorter processes keep arriving, constantly pushing the longer processes down the queue.",
      },
      {
        q: "Preemptive version of SJF is:",
        options: ["FCFS", "Priority", "Shortest Remaining Time First", "Round Robin"],
        answer: 2,
        difficulty: "Hard",
        explanation: "Shortest Remaining Time First (SRTF) is the preemptive version of SJF. If a new process arrives with a shorter execution time than what is remaining of the current process, the CPU is preempted.",
      },
      {
        q: "Round Robin scheduling uses:",
        options: ["Priority number", "Time quantum", "FIFO queue", "Semaphore"],
        answer: 1,
        difficulty: "Easy",
      },
      {
        q: "If the time quantum is very large in Round Robin, it behaves like:",
        options: ["SJF", "Priority", "FCFS", "LIFO"],
        answer: 2,
        difficulty: "Hard",
        explanation: "If the time quantum is larger than the longest process's burst time, every process will finish in its first time slice, exactly mimicking FCFS.",
      },
      {
        q: "A race condition occurs when:",
        options: [
          "Two processes run slowly",
          "Multiple processes access shared data concurrently",
          "CPU is idle",
          "Deadlock occurs",
        ],
        answer: 1,
        difficulty: "Easy",
      },
      {
        q: "The critical section problem deals with:",
        options: ["CPU scheduling", "Memory allocation", "Process synchronization", "Disk management"],
        answer: 2,
        difficulty: "Easy",
      },
      {
        q: "Peterson's solution is used for:",
        options: [
          "Deadlock detection",
          "Mutual exclusion for two processes",
          "Paging",
          "Disk scheduling",
        ],
        answer: 1,
        difficulty: "Easy",
      },
      {
        q: "Which hardware instruction is used for synchronization?",
        options: ["MOV", "ADD", "Test-and-Set", "JMP"],
        answer: 2,
      },
      {
        q: "A mutex lock provides:",
        options: ["Multiprocessing", "Mutual exclusion", "Deadlock", "Swapping"],
        answer: 1,
        difficulty: "Easy",
      },
      {
        q: "A semaphore is:",
        options: [
          "Hardware device",
          "Integer variable used for synchronization",
          "Scheduling algorithm",
          "Disk block",
        ],
        answer: 1,
        difficulty: "Easy",
      },
      {
        q: "Binary semaphore is also called:",
        options: ["Counting semaphore", "Mutex", "Monitor", "Signal"],
        answer: 1,
        difficulty: "Hard",
        explanation: "A binary semaphore only takes values 0 and 1, making it functionally equivalent to a mutual exclusion (mutex) lock for protecting a critical section.",
      },
      {
        q: "A monitor provides:",
        options: [
          "Low-level synchronization",
          "High-level synchronization construct",
          "Disk management",
          "Paging",
        ],
        answer: 1,
        difficulty: "Hard",
        explanation: "Monitors are high-level language constructs that encapsulate shared variables and the procedures that operate on them, automatically providing mutual exclusion.",
      },
      {
        q: "Producer–Consumer problem is solved using:",
        options: ["Paging", "Semaphores", "Swapping", "Scheduling"],
        answer: 1,
        difficulty: "Hard",
        explanation: "Semaphores are used to keep track of the number of empty and full slots in the buffer, and to ensure mutual exclusion when accessing the shared buffer.",
      },
      {
        q: "Readers–Writers problem deals with:",
        options: ["CPU scheduling", "Memory allocation", "Shared database access", "Disk scheduling"],
        answer: 2,
        difficulty: "Hard",
        explanation: "It's a classic synchronization problem where multiple readers can access a shared resource (like a database) simultaneously, but a writer must have exclusive access.",
      },
      {
        q: "Dining philosophers problem is an example of:",
        options: ["Scheduling", "Deadlock", "Paging", "Swapping"],
        answer: 1,
        difficulty: "Easy",
      },
      {
        q: "Deadlock occurs when ALL of these hold simultaneously:",
        options: [
          "CPU idle",
          "Mutual exclusion + hold and wait + no preemption + circular wait",
          "Only circular wait",
          "Only mutual exclusion",
        ],
        answer: 1,
        difficulty: "Easy",
      },
      {
        q: "Which is NOT a condition for deadlock?",
        options: ["Mutual exclusion", "Preemption allowed", "Circular wait", "Hold and wait"],
        answer: 1,
        difficulty: "Hard",
        explanation: "Deadlock requires 'No preemption' as one of its four necessary conditions. If preemption is allowed, resources can be forcibly removed, breaking the deadlock.",
      },
      {
        q: "Banker's algorithm is used for:",
        options: ["Deadlock detection", "Deadlock avoidance", "Scheduling", "Paging"],
        answer: 1,
        difficulty: "Easy",
      },
      {
        q: "In Banker's algorithm, the system must remain in a:",
        options: ["Deadlock state", "Safe state", "Unsafe state", "Waiting state"],
        answer: 1,
        difficulty: "Hard",
        explanation: "Banker's algorithm is an avoidance strategy that only grants resource requests if they leave the system in a 'safe state', where a sequence of processes exists that can finish without deadlock.",
      },
      {
        q: "Deadlock detection algorithm is used when:",
        options: ["Avoidance is not applied", "Prevention applied", "Only one process exists", "No resource sharing"],
        answer: 0,
        difficulty: "Hard",
        explanation: "If a system doesn't use deadlock prevention or avoidance (like Banker's algorithm), it may allow deadlocks to occur and must periodically run a detection algorithm to find and recover from them.",
      },
      {
        q: "Address space refers to:",
        options: ["Physical memory", "Logical memory of a process", "Disk blocks", "Cache"],
        answer: 1,
        difficulty: "Hard",
        explanation: "A process's address space is the set of logical (virtual) addresses that it is allowed to use, isolating its memory from other processes.",
      },
      {
        q: "Logical address is generated by:",
        options: ["Memory", "CPU", "Disk", "Monitor"],
        answer: 1,
        difficulty: "Hard",
        explanation: "The CPU generates logical (or virtual) addresses during program execution. These are then translated into physical addresses by the Memory Management Unit (MMU).",
      },
      {
        q: "Swapping moves processes between:",
        options: ["Cache and CPU", "RAM and Disk", "Registers", "Stack and Heap"],
        answer: 1,
        difficulty: "Easy",
      },
      {
        q: "Fixed partition memory allocation suffers from:",
        options: ["External fragmentation", "Internal fragmentation", "No fragmentation", "Deadlock"],
        answer: 1,
        difficulty: "Hard",
        explanation: "In fixed partitioning, memory is divided into fixed-size blocks. If a process needs less memory than the block size, the remaining space in the block is wasted (internal fragmentation).",
      },
      {
        q: "Variable partition allocation suffers from:",
        options: ["Internal fragmentation", "External fragmentation", "No issue", "Deadlock"],
        answer: 1,
        difficulty: "Hard",
        explanation: "In variable partitioning, memory blocks are allocated dynamically. As processes exit, free holes are left scattered, which might collectively be large enough but are not contiguous (external fragmentation).",
      },
      {
        q: "In segmentation, memory is divided based on:",
        options: ["Fixed size", "Logical units", "Equal blocks", "Random blocks"],
        answer: 1,
        difficulty: "Hard",
        explanation: "Segmentation divides memory into logical variable-size units (segments) like functions, arrays, or objects, which align with the programmer's view of memory.",
      },
      {
        q: "Page size in paging is:",
        options: ["Variable", "Fixed", "Infinite", "Dynamic"],
        answer: 1,
        difficulty: "Hard",
        explanation: "In paging, physical memory is divided into fixed-size blocks called frames, and logical memory is divided into blocks of the same fixed size called pages.",
      },
      {
        q: "Paging eliminates:",
        options: [
          "Internal fragmentation",
          "External fragmentation",
          "Both fragmentations",
          "Segmentation",
        ],
        answer: 1,
        difficulty: "Easy",
      },
      {
        q: "Virtual memory allows:",
        options: [
          "Smaller memory usage",
          "Larger logical address space than physical memory",
          "No disk usage",
          "No swapping",
        ],
        answer: 1,
        difficulty: "Easy",
      },
      {
        q: "Demand paging loads pages:",
        options: ["At startup", "When required", "Never", "Randomly"],
        answer: 1,
        difficulty: "Easy",
      },
      {
        q: "Page fault occurs when:",
        options: ["Page is in memory", "Page is not in memory", "CPU idle", "Disk full"],
        answer: 1,
        difficulty: "Hard",
        explanation: "A page fault is an exception raised when a process tries to access a page that is mapped in its logical address space but not currently loaded in physical RAM.",
      },
      {
        q: "Thrashing occurs due to:",
        options: ["Excessive paging", "CPU overuse", "Disk formatting", "Scheduling"],
        answer: 0,
        difficulty: "Hard",
        explanation: "Thrashing happens when a system is spending more time paging (swapping pages in and out of disk) than executing actual process instructions.",
      },
      {
        q: "Magnetic disks use:",
        options: ["Flash memory", "Rotating platters", "RAM", "Registers"],
        answer: 1,
        difficulty: "Hard",
        explanation: "Magnetic disks (HDDs) use circular, magnetically coated platters that rotate at high speeds, with read/write heads moving across their surface.",
      },
      {
        q: "SSD is faster than HDD because:",
        options: ["It has moving parts", "No mechanical movement", "Larger size", "More sectors"],
        answer: 1,
        difficulty: "Easy",
      },
      {
        q: "SSTF disk scheduling selects the request with:",
        options: ["Highest priority", "Shortest seek time", "Longest seek", "FIFO order"],
        answer: 1,
        difficulty: "Hard",
        explanation: "Shortest Seek Time First (SSTF) selects the pending disk request that is closest to the current head position, minimizing immediate head movement.",
      },
      {
        q: "SCAN disk scheduling is also called:",
        options: ["FIFO", "Elevator algorithm", "SSTF", "FCFS"],
        answer: 1,
        difficulty: "Easy",
      },
      {
        q: "Disk formatting prepares a disk for:",
        options: ["Scheduling", "Data storage", "Swapping", "Paging"],
        answer: 1,
        difficulty: "Easy",
      },
      {
        q: "If frame size is 4KB then a paging system with page table entry of 2 bytes can address _____ bytes of physical memory.",
        options: ["2^12", "2^16", "2^18", "2^28"],
        answer: 3,
        difficulty: "Hard",
        explanation: "2-byte PTE → 2¹⁶ possible frame numbers. Each frame = 4KB = 2¹² bytes. Total addressable = 2¹⁶ × 2¹² = 2²⁸ bytes.",
      },
      {
        q: "Calculate the internal fragmentation if page size is 4KB and process size is 103KB.",
        options: ["3KB", "4KB", "1KB", "2KB"],
        answer: 2,
        difficulty: "Hard",
        explanation: "103KB / 4KB = 25 full pages + 3KB remainder. The last page wastes 4KB − 3KB = 1KB of internal fragmentation.",
      },
      {
        q: "Which of the following scheduling policy is likely to improve interactiveness?",
        options: ["FCFS", "Round Robin", "Shortest Process Next", "Priority Based Scheduling"],
        answer: 1,
        difficulty: "Easy",
      },
      {
        q: "In a system using single processor, a new process arrives at the rate of 12 processes per minute and each such process requires 5 seconds of service time. What is the percentage of CPU utilization?",
        options: ["41.66", "100.00", "240.00", "60.00"],
        answer: 1,
        difficulty: "Hard",
        explanation: "12 processes/min × 5 sec each = 60 sec of CPU work per minute. Since 1 minute = 60 sec, the CPU is 100% utilized.",
      },
      {
        q: "A system has two processes and three identical resources. Each process needs a maximum of two resources. This could cause:",
        options: ["Deadlock is possible", "Deadlock is not possible", "Starvation may be present", "Thrashing"],
        answer: 1,
        difficulty: "Hard",
        explanation: "With 3 resources and max need of 2 each, at least one process can always get both resources and finish. Deadlock is impossible here.",
      },
      {
        q: "A disk has 400 cylinders (0–399). The disk arm is at cylinder 58 with pending requests for cylinders 66, 349, 201, 110, 38, 84, 226, 70, 86. Using SSTF, cylinder 86 is serviced after servicing _____ requests.",
        options: ["1", "2", "3", "4"],
        answer: 3,
        difficulty: "Hard",
        explanation: "SSTF order from 58: 66→70→84→86. So cylinder 86 is the 4th request serviced (after 66, 70, 84).",
      },
      {
        q: "Which of the following is true with regard to Round Robin scheduling technique?",
        options: ["Responds poorly to short process with small time quantum", "Works like SJF for larger time quantum", "Does not use a prior knowledge of burst times of processes", "Ensure that the ready queue is always of the same size"],
        answer: 2,
        difficulty: "Hard",
        explanation: "Round Robin assigns equal time slices to all processes without needing to know their burst times. It purely relies on time quantum and arrival order.",
      },
      // --- Exam paper questions ---
      {
        q: "In the _____ algorithm, the disk arm goes as far as the final request in each direction, then reverses direction immediately without going to the end of the disk.",
        options: ["LOOK", "SCAN", "C-SCAN", "C-LOOK"],
        answer: 0,
        difficulty: "Easy",
        explanation: "LOOK is like SCAN but smarter — it only goes as far as the last pending request in each direction, then reverses, without traveling all the way to the disk's end.",
      },
      {
        q: "The systematic procedure for providing the CPU to a new process is known as:",
        options: ["Synchronization", "Semaphore", "Context Switching", "Deadlock"],
        answer: 2,
        difficulty: "Easy",
        explanation: "Context switching is the mechanism of saving the state of the currently running process and restoring the state of the next process to be given CPU time.",
      },
      {
        q: "For an effective operating system, when should deadlock be checked?",
        options: [
          "Every time a resource request is made at fixed time intervals",
          "At fixed time intervals only",
          "Never",
          "Every time a resource request is made",
        ],
        answer: 0,
        difficulty: "Hard",
        explanation: "The best strategy combines both: check whenever a resource request is made (to catch it early) and also at fixed intervals (to handle cases not triggered by requests).",
      },
      {
        q: "System calls of the operating system provide an interface to:",
        options: ["Programs", "Processes", "Services", "Utilities"],
        answer: 2,
        difficulty: "Easy",
        explanation: "System calls are the programming interface to the services (file I/O, process control, communication, etc.) provided by the operating system kernel.",
      },
      {
        q: "There are 200 tracks on a disk. Pending requests: 36, 69, 167, 76, 42, 51, 126, 12, 199. Arm at track 100 moving toward 200. Sequence served: 126, 167, 199, 12, 36, 42, 51, 69, 76. Which scheduling policy is this?",
        options: ["LOOK", "SCAN", "C-SCAN", "FCFS"],
        answer: 2,
        difficulty: "Hard",
        explanation: "C-SCAN services requests in one direction to the highest track, then jumps back to the lowest track (without servicing) and scans upward again. The sequence confirms this jump-back behavior.",
      },
      {
        q: "A process refers to 5 pages A, B, C, D, E in order: A, B, C, D, A, B, E, A, B, C, E. Using FIFO page replacement with 3 frames (initially empty), the number of page faults is:",
        options: ["11", "10", "9", "8"],
        answer: 2,
        difficulty: "Hard",
        explanation: "Tracing FIFO with 3 frames: A(fault), B(fault), C(fault), D(fault→A evicted), A(fault→B evicted), B(fault→C evicted), E(fault→D evicted), A(hit), B(hit), C(fault→E evicted), E(fault→A evicted). Total = 9 page faults.",
      },
    ],
  },

  // =====================================================================
  {
    title: "Module V",
    subject: "Digital Signal Processing",
    summary: "Discrete-time signals and systems, LTI systems, Z-transform, and Fourier transforms (DFT, FFT algorithms like Radix-2). Design and realization of digital filters (FIR, IIR), bilinear transformation, and quantization effects.",
    questions: [
      {
        q: "Which of the following is an example of an elementary signal?",
        options: ["Random signal", "Sinusoidal signal", "Noise signal", "Speech signal"],
        answer: 1,
      },
      {
        q: "A discrete-time signal is represented as:",
        options: ["x(t)", "x[n]", "x(s)", "x(ω)"],
        answer: 1,
      },
      {
        q: "A signal x[n] is classified as discrete-time because:",
        options: [
          "Discrete amplitude values",
          "Integer-valued independent variable",
          "Periodic nature",
          "Finite duration",
        ],
        answer: 1,
      },
      {
        q: "Process of converting a continuous-time signal into a discrete-time signal is:",
        options: ["Filtering", "Sampling", "Convolution", "Quantization"],
        answer: 1,
      },
      {
        q: "To avoid aliasing, the sampling frequency fs must satisfy:",
        options: ["fs < 2·fmax", "fs = fmax", "fs ≥ 2·fmax", "fs = 0"],
        answer: 2,
      },
      {
        q: "An analog signal is sampled at 8 kHz. Sampling period is:",
        options: ["0.125 ms", "8 ms", "125 μs", "1.25 ms"],
        answer: 0,
      },
      {
        q: "Which block converts an analog signal into a digital signal in a DSP system?",
        options: ["DAC", "ADC", "Filter", "FFT processor"],
        answer: 1,
      },
      {
        q: "Quantization noise is introduced during:",
        options: ["Sampling", "Filtering", "Quantization (ADC)", "Reconstruction"],
        answer: 2,
      },
      {
        q: "An LTI system has impulse response h(t). If x(t) = 3δ(t − 2), output y(t) is:",
        options: ["h(t − 2)", "3h(t)", "3h(t − 2)", "h(3t − 2)"],
        answer: 2,
      },
      {
        q: "A system is 'Linear' if it follows:",
        options: [
          "Inversion and Scaling",
          "Superposition and Homogeneity",
          "Causality and Stability",
          "Differentiation and Integration",
        ],
        answer: 1,
      },
      {
        q: "DFT stands for:",
        options: [
          "Digital Filter Transform",
          "Discrete Fourier Transform",
          "Dual Frequency Token",
          "Direct Fourier Technique",
        ],
        answer: 1,
      },
      {
        q: "An 8-point DFT computed directly requires approximately how many complex multiplications?",
        options: ["8", "32", "64", "128"],
        answer: 2,
      },
      {
        q: "Which property guarantees that signal energy in time domain equals energy in transform domain?",
        options: ["Linearity", "Time invariance", "Parseval's theorem", "Periodicity"],
        answer: 2,
      },
      {
        q: "The Twiddle factor WN in DFT is defined as:",
        options: ["e^(−j2π/N)", "e^(j2π/N)", "sin(2π/N)", "cos(2π/N)"],
        answer: 0,
      },
      {
        q: "Given X(k) = DFT{x(n)}, the IDFT is computed by:",
        options: [
          "Summation using the same exponential kernel",
          "Conjugation of X(k)",
          "Use of inverse exponential with scaling factor 1/N",
          "Time reversal of X(k)",
        ],
        answer: 2,
      },
      {
        q: "Two length-4 sequences convolved using a 4-point DFT (no zero padding) produces:",
        options: ["Linear convolution", "Circular convolution", "Aperiodic convolution", "Valid convolution"],
        answer: 1,
      },
      {
        q: "Circular convolution gives linear filtering when sequences are:",
        options: ["Padded with zeros", "Multiplied by a window", "Integrated", "Finite and equal to 1"],
        answer: 0,
      },
      {
        q: "Result of circular convolution of {1,1} and {1,1} is:",
        options: ["{1,1}", "{2,2}", "{1,2,1}", "{0,0}"],
        answer: 1,
      },
      {
        q: "Which methods are used for filtering long data sequences?",
        options: [
          "Radix-2 and Radix-4",
          "Overlap-save and Overlap-add",
          "Impulse Invariance and Bilinear",
          "DFT and IDFT",
        ],
        answer: 1,
      },
      {
        q: "A length-10000 sequence is filtered via FFT-based blocks. Overlap-Add/Save are used to:",
        options: [
          "Reduce quantization noise",
          "Efficiently perform linear convolution using FFT blocks",
          "Avoid spectral leakage",
          "Eliminate aliasing",
        ],
        answer: 1,
      },
      {
        q: "Radix-2 FFT reduces computational complexity of an N-point DFT from O(N²) to:",
        options: ["O(N)", "O(N log₂ N)", "O(log N)", "O(N³)"],
        answer: 1,
      },
      {
        q: "Radix-2 FFT algorithms require the number of samples to be:",
        options: ["Prime", "Odd", "Power of 2", "Even"],
        answer: 2,
      },
      {
        q: "In an 8-point Radix-2 FFT, how many stages of butterflies are required?",
        options: ["2", "3", "4", "8"],
        answer: 1,
      },
      {
        q: "In Decimation-in-Time (DIT) FFT, the input sequence is in:",
        options: [
          "Bit-reversed order",
          "Natural order",
          "Sorted by magnitude",
          "Shifted by N/2",
        ],
        answer: 0,
      },
      {
        q: "What is the primary characteristic of an IIR filter?",
        options: [
          "Finite number of non-zero terms",
          "Uses feedback (recursive)",
          "Impulse response always zero after 10 samples",
          "Always unstable",
        ],
        answer: 1,
      },
      {
        q: "Bilinear Transformation is used to design IIR filters by mapping:",
        options: [
          "s-plane to z-plane",
          "z-plane to time domain",
          "Analog frequencies to infinity",
          "Digital filters to FIR filters",
        ],
        answer: 0,
      },
      {
        q: "When using bilinear transformation, which effect must be compensated?",
        options: ["Time-domain aliasing", "Frequency warping", "Phase distortion", "Impulse truncation"],
        answer: 1,
      },
      {
        q: "Which structure directly implements the difference equation of a system?",
        options: ["Cascade form", "Parallel form", "Direct form", "Lattice form"],
        answer: 2,
      },
      {
        q: "Which realization is least sensitive to coefficient quantization for a high-order IIR filter?",
        options: ["Direct Form-I", "Direct Form-II", "Cascade of second-order sections", "Lattice FIR"],
        answer: 2,
      },
      {
        q: "An FIR filter has linear phase if its impulse response is:",
        options: ["Arbitrary", "Causal", "Symmetric or anti-symmetric", "Infinite"],
        answer: 2,
      },
      {
        q: "Linear phase response is characteristic of which filter type?",
        options: ["IIR Filter", "FIR Filter", "All-pass Filter", "Butterworth Filter"],
        answer: 1,
      },
      {
        q: "FIR filter h[n] = {1, 2, 3, 2, 1} exhibits:",
        options: ["Nonlinear phase", "Minimum phase", "Linear phase", "Zero phase"],
        answer: 2,
      },
      {
        q: "Which FIR design technique is based on truncation of the ideal impulse response?",
        options: ["Frequency sampling", "Window method", "Parks–McClellan", "Least squares"],
        answer: 1,
      },
      {
        q: "Which window provides the narrowest main lobe?",
        options: ["Rectangular window", "Hamming window", "Hanning window", "Blackman window"],
        answer: 0,
      },
      {
        q: "If an FIR window length is doubled, the most significant effect is:",
        options: [
          "Increased passband ripple",
          "Wider transition band",
          "Narrower transition band",
          "Increased quantization noise",
        ],
        answer: 2,
      },
      {
        q: "Harvard architecture separates:",
        options: ["CPU and ALU", "Program and data memory", "Cache and RAM", "Input and output"],
        answer: 1,
      },
      {
        q: "Due to Harvard architecture, in a single clock cycle a DSP can perform:",
        options: [
          "Two data fetches simultaneously",
          "Instruction fetch and data fetch simultaneously",
          "Two instructions executed simultaneously",
          "Parallel ALU operations only",
        ],
        answer: 1,
      },
      {
        q: "MAC stands for:",
        options: [
          "Memory Access Control",
          "Multiply-Accumulate",
          "Message Authentication Code",
          "Micro-Address Counter",
        ],
        answer: 1,
      },
      {
        q: "Σ x[n]·h[n] is most efficiently computed by which DSP hardware?",
        options: ["Shifter", "Comparator", "Multiply-Accumulate (MAC) unit", "Address generation unit"],
        answer: 2,
      },
      {
        q: "A 5-stage DSP pipeline (10 ns/stage) takes how long to complete 10 instructions (ignoring overhead)?",
        options: ["100 ns", "140 ns", "500 ns", "50 ns"],
        answer: 1,
      },
      {
        q: "TMS320C67xx is an example of:",
        options: ["8-bit Microcontroller", "Floating-point DSP", "Fixed-point only Processor", "FPGA"],
        answer: 1,
      },
      {
        q: "Q15 fixed-point format max positive value is approximately:",
        options: ["0.99997", "1", "32767", "1.999"],
        answer: 0,
      },
      {
        q: "Switching from floating-point to fixed-point makes which design requirement critical?",
        options: [
          "Instruction pipelining",
          "Scaling and overflow management",
          "Cache coherence",
          "Interrupt latency",
        ],
        answer: 1,
      },
      {
        q: "Finite word length effects in IIR filters can cause:",
        options: ["Limit cycle oscillations", "Linear phase", "Stability improvement", "Reduced noise"],
        answer: 0,
      },
      {
        q: "An IIR filter with zero input shows constant non-zero output. This is:",
        options: ["Overflow oscillation", "Limit cycle oscillation", "Aliasing", "Quantization noise"],
        answer: 1,
      },
      {
        q: "An IIR filter becomes unstable after coefficient quantization due to:",
        options: ["Round-off noise", "Pole displacement", "Window leakage", "Spectral folding"],
        answer: 1,
      },
      {
        q: "The computational procedure for Decimation in Frequency algorithm takes:",
        options: ["log₂N stages", "2·log₂N stages", "log₂N² stages", "log₂(N/2) stages"],
        answer: 0,
        difficulty: "Hard",
        explanation: "Both DIT and DIF FFT algorithms require log₂N stages of butterfly operations. Each stage processes N/2 butterflies.",
      },
      {
        q: "The region of convergence of x/(1+2x+x²) is:",
        options: ["0", "1", "Negative", "Positive"],
        answer: 1,
        difficulty: "Hard",
        explanation: "x/(1+2x+x²) = x/(1+x)². The poles are at x = -1. The ROC excludes the pole, so |x| < 1 converges, giving ROC boundary at 1.",
      },
      {
        q: "A signal x[n] is anti-symmetric or odd when:",
        options: ["x[−n] = x[n]·x[n]", "x[n] = −x[n]", "x[n] = [x[n]]²", "x[−n] = −x[n]"],
        answer: 3,
        difficulty: "Easy",
      },
      {
        q: "For the calculation of N-point DFT, Radix-2 FFT algorithm requires approximately:",
        options: ["2N·log₂N² computations", "(N·log₂N)²/2 computations", "(N·log₂N)/2 computations", "(N·log₂2N)/2 computations"],
        answer: 2,
        difficulty: "Hard",
        explanation: "Radix-2 FFT has log₂N stages, each with N/2 butterflies (1 multiplication each). Total complex multiplications ≈ (N/2)·log₂N = (N·log₂N)/2.",
      },
      {
        q: "The scaling of a sequence x[n] by a factor α is given by:",
        options: ["y[n] = α·[x[n]]²", "y[n] = α·x[n²]", "y[n] = α·x[n]", "y[n] = x[n]·x[−n]"],
        answer: 2,
        difficulty: "Easy",
      },
      {
        q: "In cascade form of realization, how many bits should be used to represent the FIR filter coefficients to avoid the quantization effect?",
        options: ["5 to 10", "12 to 14", "20 to 24", "28 to 40"],
        answer: 1,
        difficulty: "Hard",
        explanation: "12–14 bits provides sufficient precision for cascade FIR coefficients to minimize quantization effects while keeping hardware practical.",
      },
      {
        q: "The impulse response of a continuous time system is h(t) = δ(t−1) + δ(t−3). The value of the step response at t = 2 is:",
        options: ["0", "1", "2", "3"],
        answer: 1,
        difficulty: "Hard",
        explanation: "Step response = integral of h(t) from -∞ to t. At t=2: δ(t-1) has fired (contributes 1), but δ(t-3) has not (t=2 < 3). So step response = 1.",
      },
      {
        q: "A 1 kHz sinusoidal signal is ideally sampled at 1500 samples/sec and the sampled signal is passed through an ideal low-pass filter with cut-off frequency 800 Hz. The output signal has the frequency:",
        options: ["0 Hz", "0.75 kHz", "0.5 kHz", "0.25 kHz"],
        answer: 2,
        difficulty: "Hard",
        explanation: "fs=1500 Hz, f=1000 Hz. Since f > fs/2 (750 Hz), aliasing occurs. Alias frequency = fs − f = 1500 − 1000 = 500 Hz = 0.5 kHz, which passes through the 800 Hz LPF.",
      },
      // --- New additions ---
      {
        q: "For an N point FFT algorithm with N = 2^m, which one of the following statements is true?",
        options: [
          "It is not possible to construct a signal flow graph with both input and output in normal order",
          "The number of butterflies in the m-th stage is N/m",
          "In-place computation requires storage of only 2N node data",
          "Computation of a butterfly requires only one complex multiplication",
        ],
        answer: 3,
        difficulty: "Hard",
        explanation: "Each butterfly operation in the Radix-2 FFT involves multiplying one input by a twiddle factor (1 complex multiplication) and performing 2 complex additions.",
      },
      {
        q: "The transformation technique in which there is one-to-one mapping from s-domain to z-domain is:",
        options: ["Approximation of derivatives", "Impulse invariance method", "Bilinear transformation method", "Backward difference for the derivative"],
        answer: 2,
        difficulty: "Hard",
        explanation: "Bilinear transformation maps the entire jΩ axis in s-plane to the unit circle in z-plane without aliasing, providing a one-to-one mapping.",
      },
      {
        q: "Which of the following methods are used to convert an analog filter into a digital filter?",
        options: ["Approximation of Derivatives", "Bilinear transformation", "Impulse invariance", "All of the mentioned"],
        answer: 3,
        difficulty: "Easy",
      },
      {
        q: "A digital filter is said to be an IIR if:",
        options: ["It oscillates", "All its poles lie outside the unit circle", "Present output depends on previous output", "One or more denominator coefficient is zero"],
        answer: 2,
        difficulty: "Hard",
        explanation: "IIR (Infinite Impulse Response) filters use feedback — the current output depends on past outputs, making the impulse response theoretically infinite.",
      },
      {
        q: "The 4-point Discrete Fourier Transform (DFT) of a discrete time sequence {1, 0, 2, 3} is:",
        options: ["[0, -2+2j, 2, -2-2j]", "[2, 2+2j, 6, 2-2j]", "[6, 1-3j, 2, 1+3j]", "[6, -1+3j, 0, -1-3j]"],
        answer: 3,
        difficulty: "Hard",
        explanation: "X(0)=1+0+2+3=6. X(1)=1+0·(-j)+2·(-1)+3·(j)=-1+3j. X(2)=1+0·(-1)+2·(1)+3·(-1)=0. X(3)=1+0·(j)+2·(-1)+3·(-j)=-1-3j.",
      },
    ],
  },

]
